### ISSUE TITLE
SPLATT API

### ISSUE THREAD

**Issue by ShadenSmith** [hpcgarage/AdaTM#2]
I would be happy to discuss the API functionality that you AdaTM requires from SPLATT. I am currently working on releasing a much improved SPLATT v2 and hope to include functionality that you find useful.

Can you point me to some functionality that you would like exposed?

**Comment by fruitfly1026** [comment]
Yes, Shaden! I planed to send you an email after the conference. Generally, all functions in the CSF MTTKRP, for root, leaf, and internal nodes. and some others. I'll leave this issue open, and refill you the details later.

**Comment by ShadenSmith** [comment]
A public discussion may be better than email, as the public shame may be a better motivator for me :-).

**Comment by fruitfly1026** [comment]
nono. Not your fault, it's our library is an idea based on your implementation to optimize inside CP, other work directly calling MTTKRP and CP will not have this issue. You're doing very well! But being a motivator is nice if it works for you. :-)

**Comment by fruitfly1026** [comment]
Hi Shaden, sorry for my late response. For SPALTT 1.1.1, basically the functions I need are all the functions called by "cpd_als_iterate", partial supporting functions called by "mttkrp_csf", and csf format building functions. It's a lot... And many of them are not necessary to provide to application users. So I guess it may be the best to stay as a patch now. :-) I'll supply a direct downloadable version of SPLATT 1.1.1 from the README file to ensure it runs, is it ok? Thanks!

**Comment by ShadenSmith** [comment]
Yes, that sounds like a bit more than I was planning to expose in the API right now. You're more than welcome to distribute the already-patched version of AdaTM+SPLATT  v1.1.1 on your website, though!

**Comment by fruitfly1026** [comment]
Thanks Shaden. We'll discuss this. :-)
